### ISSUE TITLE
純靠北工程師 v1.0 To-Do List

### ISSUE THREAD

**Issue by horowolf** [init-engineer/init.engineer-iOS-App#5]
~版權頁面製作~
~icon版權聲明~
- [x] 隱私權政策(乾太要做的)
- [x] 文章列表詳細內容製作（不需使用匿名動物 By @tico88612）（Assigner：@tico88612）
  - [x] 文章留言區 https://github.com/init-engineer/init.engineer-iOS-App/commit/8e4bef87ca24a7d402e23a23e6cc21c5607313e8 https://github.com/init-engineer/init.engineer-iOS-App/commit/9a7843ad658aa989d3f0a292fad3eb4cd3b4d30b https://github.com/init-engineer/init.engineer-iOS-App/commit/d53171fd5144a923c07c44a17c28adf357d01c1e https://github.com/init-engineer/init.engineer-iOS-App/commit/ebff4ec73b9e1bcfee93e5878439a3cfc1cacd43
- [x] 首頁中加入新的兩個社群平台，Tumblr、Telegram。https://github.com/init-engineer/init.engineer-iOS-App/commit/6361a708246f50f30145d3a8b26eb60cc8176782
- [x] 審核文章詳細內容製作 #8 
- [x] 審核文章的 cell 細節確認 #8 
- [x] 解決ReviewList的reload問題，當投下票後，會觸發list的更新，因為沒有辦法對特定文章的資料更新，只能全部reload，因此造成無法回到之前list的位置。(list中的page2開始是明顯的)
- [x] 儀表板內容製作
  - [x] 使用者資訊 https://github.com/init-engineer/init.engineer-iOS-App/commit/26ae2f2a8105ea604ebdd2f017d532245990dc69
  - [x] 使用者貼文
- [x] Loading的動作物件，用於表示正在下載
  - [x] 確認使用Loading的地方並加入
  - [x] 隨機使用一個Loading的類型
~移除staging~
~UI 確認：字體、顏色，並且弄到 constants~
- [x] AdMob相關隱私權問題
- [x] Code review
- [x] APP流暢度確認

**Comment by horowolf** [comment]
* We offer an extensive free tier, all we ask is for you to add a link back to icons8.com crediting us in the final work.
https://www.figma.com/community/plugin/791103617505812222/Icons8-Free-Icons
